name: Swace Lab Test pipeline
trigger: none
parameters:
  - name: environment
    displayName: 'Select Test Environment'
    type: string
    default: 'UAT'
    values: 
      - 'UAT'
      - 'DEV'
  - name: Scope
    displayName: 'Test Scope'
    type: string
    default: 'sanity'
    values:
      - 'sanity'
      - 'smoke'
      - 'regression'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: PlaywrightTests
    displayName: 'Run Playwright Tests'
    steps:
      - checkout: self

      - task: NodeTool@0
        inputs:
          versionSpec: '22'
        displayName: 'Setup Node.js'

      - script: npm ci
        displayName: 'Install dependencies'

      - script: npx playwright install --with-deps chromium
        displayName: 'Install Playwright browsers'

      - script: npx bddgen
        displayName: 'Generate BDD tests'

      - script: npx playwright test
        displayName: 'Run Playwright tests'

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        condition: always()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results/junit.xml'
          testRunTitle: '$(Parameters.environment) - $(Parameters.Scope)'
          mergeTestResults: true
          failTaskOnFailedTests: true

      - task: PublishPipelineArtifact@1
        condition: always()
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/playwright-report'
          artifact: 'HTML Report'
          publishLocation: 'pipeline'
        displayName: 'Publish HTML Report'

      - task: PublishBuildArtifacts@1
        condition: always()
        inputs:
          pathToPublish: '$(System.DefaultWorkingDirectory)/playwright-report'
          artifactName: 'playwright-report'
          publishLocation: 'Container'
        displayName: 'Upload Playwright report'

      - task: PublishBuildArtifacts@1
        condition: always()
        inputs:
          pathToPublish: '$(System.DefaultWorkingDirectory)/test-results'
          artifactName: 'test-results'
          publishLocation: 'Container'
        displayName: 'Upload test results'